COLUMNS:
  work_year:             int64 
  experience_level:      object
  employment_type:         object
  job_title:               object
  salary:                  int64 
  salary_currency:         object 
  employee_residence:      object
  remote_ratio:            int64 
  company_location:        object
  company_size:            object
  salary_in_usd:           int64


TARGET_COLUMN:
  name: salary_in_usd